### PR TITLE
evoting dapp on avalanche c-chain using truffle

### PR DESCRIPTION
**Pull request by rajranjan0608**
# Description*

I have added a tutorial to build an e-voting decentralised application on Avalanche's Fuji test network using Trufflesuite.

## Type of change*

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## This PR created for* - 
- [x] DataHub Official Docs (Network Documentation, API docs etc.) changes/updates/fixes
- [x] Figment Learn Docs (Pathway, Tutorials, New Tutorials etc.) changes/updates/fixes

# How Has This Been Tested? (If Applicable)

* Firmware version: 5.7.0-kali1-amd64 
* OS: Kali GNU/Linux Rolling
* Network/Protocol: Avalanche
* SDK: Trufflesuite

# Checklist*:

- [x] I updated the `SUMMARY.md` file (FYI, It's needed only when you're adding/creating a new file like submitting a new tutorial, pathway section)
- [x] I checked and read the contribution guide before making this PR [**HERE**](https://docs.google.com/document/d/13LWLrWzZ34M0ldWGeDANcWxw9nEWk3AX3VwXRBIOs1M/edit)  
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by yash-sharma1 — CHANGES_REQUESTED** [review]
@rajranjan0608 Appreciate your work, there are few things which need to be change - 

- Add the "About the Author" section before the introduction and give your short & sweet introduction in that section along with the link to social handles. 
- Make the introduction more catchy currently it looks like it's the intro of only truffle not of the project which we're going to build in this tutorial. So making it more specific will be good, for eg. explain what we're going to build, why, and how?
- Dependencies can be written as Prerequisites
- After the `.env` file add instructions/note to put it in `.gitignore` file 
- Add comments in the code wherever necessary to explain what part is performing which action.
- Explain the main parts/functions of code after each step where necessary.
- At the end, add the conclusion of the tutorial along with that you can add what's next, some good reads related to such projects, etc. all up to you how you can make it more interactive at the end :)
- Make sure to add edit and add a link to your tutorial in `SUMMARY.md` file to know more check this guide [HERE](https://docs.google.com/document/d/13LWLrWzZ34M0ldWGeDANcWxw9nEWk3AX3VwXRBIOs1M/edit?usp=sharing)

**Comment by rajranjan0608** [comment]
> @rajranjan0608 Appreciate your work, there are few things which need to be change -
> 
> * Add the "About the Author" section before the introduction and give your short & sweet introduction in that section along with the link to social handles.
> * Make the introduction more catchy currently it looks like it's the intro of only truffle not of the project which we're going to build in this tutorial. So making it more specific will be good, for eg. explain what we're going to build, why, and how?
> * Dependencies can be written as Prerequisites
> * After the `.env` file add instructions/note to put it in `.gitignore` file
> * Add comments in the code wherever necessary to explain what part is performing which action.
> * Explain the main parts/functions of code after each step where necessary.
> * At the end, add the conclusion of the tutorial along with that you can add what's next, some good reads related to such projects, etc. all up to you how you can make it more interactive at the end :)
> * Make sure to add edit and add a link to your tutorial in `SUMMARY.md` file to know more check this guide [HERE](https://docs.google.com/document/d/13LWLrWzZ34M0ldWGeDANcWxw9nEWk3AX3VwXRBIOs1M/edit?usp=sharing)

Hi, @yash-sharma1 . I have made the necessary changes. Please have a look at the commit f75c571cf573ecdfcf4cb713bdf5f13767f7d9fd Thank you.

**Comment by yash-sharma1** [comment]
Thanks for the quick fix and updates. I'll review it

**Review by yash-sharma1 — APPROVED** [review]

**Comment by yash-sharma1** [comment]
Looks good to me, @guillaumegaluz would like to have a look 👁️‍🗨️

**Review by yash-sharma1 — APPROVED** [review]

**Pull request merged**
