### PR TITLE
Polkadot: Create guide for Parachain Lifecycle

### PR DESCRIPTION
**Pull request by DannyS03**
The tutorial focusses on the Parachain lifecycle and includes fundamentals about parachains. More focus is found in this tutorial on parachains & parathreads. 

Any feedback for format & approach is highly encouraged.

---
- [x] My tutorial follows the [Tutorial Contribution Guidelines](https://app.gitbook.com/@figment-learn/s/learn-docs/other/tutorial-guidelines).

In particular:

- [x] I've followed the [template structure](Structure).
- [x] I've proofread the tutorial for spelling and grammar mistakes.
- [x] I've ran a linter & prettifier to format my code blocks.
- [ ] I've thoroughlly explained the code, with inline code comments and text explanations.
- [ ] I've ran the tutorial and the code works.

### CODE REVIEW

**Comment by DannyS03** [comment]
@yash-sharma1 @guillaumegaluz updated and also ready to review.

**Comment by DannyS03** [comment]
Similarly - name okay? And where is best to include the file in the list of tutorials?

**Comment by pyr0gan** [comment]
In light of your other pull request not being referenced in the SUMMARY.md file, please _make sure_ that this one is.

**Comment by DannyS03** [comment]
@pyr0gan added some changes

**Comment by DannyS03** [comment]
New file added and edits merged into patch-1 branch: https://github.com/DannyS03/datahub-learn/pull/1

**Pull request closed without merging**
