### PR TITLE
Add reward docs to transaction search

### PR DESCRIPTION
**Pull request by pacmessica**
[notion](https://www.notion.so/figmentnetworks/b47c0f8b935741d8ac28717ddeea2038?v=5e4e1d3854094b788ae2b612329f27e8&p=a07a4f65e1324c55939a12ec5a55f795)

We shouldn't merge this until after `/rewards` endpoint is exposed in datahub.

### CODE REVIEW

**Comment by pacmessica** [comment]
@Y-Folla you mentioned we should format the reward docs like the file coin api. I just noticed that after creating this PR though, but can make the changes if you want. Can you link me to the file coin api?

**Comment by pacmessica** [comment]
another things to consider - we might not support rewards on tx-search datahub api for every blockchain, so maybe rewards documentation belongs on its own page? Then we can link to rewards docs from [datahub](https://datahub.figment.io/services/terra/terra--search) only when it's available

**Comment by ajcronk** [comment]
Cosmos and Terra rewards are exposed in DataHub now - ready to merge

**Comment by Y-Folla** [comment]
@pacmessica if it has multiple methods you can use the Filecoin model https://learn.figment.io/network-documentation/filecoin/rpc-and-rest-api/miner-reputation-system-api 

If it has a single method then the Tx Search API makes more sense https://learn.figment.io/network-documentation/terra/enriched-apis/transaction-search

**Comment by pacmessica** [comment]
cool, moved it to it's own file and did the single method design

**Comment by pacmessica** [comment]
@ajcronk 

We need to reindex terra txs first to add fields necessary to calculate the rewards from txs (currently the data is missing, so reward amounts aren't accurate). Right now there's terra connectivity problems with the node which makes re-indexing stop every 10k- I'm not sure there's a ticket, but I head Matt is working on this. So we shouldn't publicize terra rewards until after this is solved.

**Pull request merged**
