### PR TITLE
A tutorial on Testing Celo Smart Contracts with Truffle

### PR DESCRIPTION
**Pull request by alexreyes**
Hi Figment team, 

I wrote a tutorial on testing smart contracts using Celo. Please review and let me know what you think!

### CODE REVIEW

**Review by yash-sharma1 — CHANGES_REQUESTED** [review]
@alexreyes please add the about author section at the starting of the tutorial if it's not from CELO Hackathon. Also adding some extra stuff/good reads related to smart contract testing will be appreciated.
Need some 👁️‍🗨️ here @pyr0gan

**Comment by alexreyes** [comment]
> @alexreyes please add the about author section at the starting of the tutorial if it's not from CELO Hackathon. Also adding some extra stuff/good reads related to smart contract testing will be appreciated.
> Need some 👁️‍🗨️ here @pyr0gan

This tutorial is not for the CELO hackathon, I wanted to contribute to another tutorial. I added the author section in my latest commit and some extra related reads.

**Review by pyr0gan — APPROVED** [review]
LGTM, not related to the Celo hackathon as @alexreyes mentioned.

**Review by yash-sharma1 — APPROVED** [review]

**Review by yash-sharma1 — COMMENTED** [review]
@alexreyes this isn't rendering on Learn seems like due to the file name `celo-testing-truffle` can you please make a new PR with ".md" file format like `celo-testing-truffle.md`

**Comment by alexreyes** [comment]
@yash-sharma1 Oh jeez I can't believe I didn't notice that!

I created a new PR here: https://github.com/figment-networks/datahub-learn/pull/65

**Comment by yash-sharma1** [comment]
> @yash-sharma1 Oh jeez I can't believe I didn't notice that!
> 
> I created a new PR here: https://github.com/figment-networks/datahub-learn/pull/65

Great!! Thanks for your quick response

**Pull request merged**
