### PR TITLE
Ubeswap celo tutorial

### PR DESCRIPTION
**Pull request by gitofdeepanshu**
Hey guys, 
This tutorial is for someone who is just getting started on Defi or needs a guide on how to use Ubeswap.
Let me know in case of any edits.
Thanks

### CODE REVIEW

**Review by pyr0gan — COMMENTED** [review]
Please have a look at my alterations @gitofdeepanshu. It may be beneficial to add some links to more comprehensive explanations about DEX or AMM concepts, or just add an informational section to the tutorial if you plan on writing more in-depth.

From the introduction, you mention the purpose being a tutorial for new Ubeswap users and also as a resource for people new to DeFi. There is not enough information here to warrant the second claim, but you can certainly add more! 

I have reviewed, and aside from the above mentioned issues this is a good and well written tutorial with only small edits required for clarity and grammar. After you have looked over my suggested edits, I believe this can be merged.

**Review by yash-sharma1 — COMMENTED** [review]
@guillaumegaluz @Y-Folla looks good to me

**Comment by yash-sharma1** [comment]
> @guillaumegaluz @Y-Folla looks good to me

Rogan added the comments to work upon so all good

**Comment by gitofdeepanshu** [comment]
Hey @pyr0gan , Thanks for the review.
I added information on AMMs and added useful links related to DeFi. 
I believe that concepts of Defi can't be explained in brief because people should know what was the need and how well does the current solutions work. Links will be good enough for anyone curious to learn more.
Let me know what you think.

**Review by pyr0gan — APPROVED** [review]
Solid explanation, thank you!

**Review by pyr0gan — APPROVED** [review]
Summary.md checked

**Pull request merged**
