### PR TITLE
Redeploy eth dapp to celo

### PR DESCRIPTION
**Pull request by gitofdeepanshu**
Hey Guys,
Just made tutorial about 'How to deploy Eth daps on Celo'. Hope you guys will like it, I am always available if you guys need to suggest any changes.
Thanks.

### CODE REVIEW

**Review by yash-sharma1 — COMMENTED** [review]
Just small addition, after the execution of each code part/file, if you can add an expected output image or paste the output from the terminal under that section will help developers & learners cross-check their code and sometimes help in debugging :)

**Comment by gitofdeepanshu** [comment]
Thanks for the feedback @yash-sharma1 , I have added images to places that seemed necessary. Please take a  look.
Will add more images in upcoming tutorials.

**Comment by yash-sharma1** [comment]
> Thanks for the feedback @yash-sharma1 , I have added images to places that seemed necessary. Please take a look.
> Will add more images in upcoming tutorials.

Sounds good, Thanks for the prompt response & update. 
@guillaumegaluz @pyr0gan can you please review the same

**Comment by guillaumegaluz** [comment]
LGTM

**Pull request merged**
