### PR TITLE
viewing key tutorial for SN

### PR DESCRIPTION
**Pull request by darwinzer0**
This is a tutorial for how to add viewing key functionality to a secret contract. It is designed as a follow-up to this tutorial: https://github.com/figment-networks/datahub-learn/blob/master/network-documentation/secret/tutorials/creating-a-secret-contract-from-scratch.md

### CODE REVIEW

**Comment by zurgl** [comment]
Hi @darwinzer0 ! smile I will be reviewing your pull request in the next 24 hours and we can get it on track for publishing on Learn.

**Comment by zurgl** [comment]
@darwinzer0 

Have you ever wonder how many times have I been through some tutorials to realize at the end "it does not compile". 

Now, when I start reading a tutorial on a plateform I do these two checks:
- Where is the repo ?
- Can I compile and run this code ?

If these two check are ok, then I read the material.

Of course, I'am playing a role and I know you have a repository storing the learing material and it will be ok.

Anyway, could you adjust your text in order to give to the learner instructions on:
- The place of the repo
- How to compile and check the code.

**Comment by darwinzer0** [comment]
thanks @zurgl, I will make those edits. This one assumes that the learner is building off of what they did in the previous tutorial, but I think it might be helpful to include a complete version of what the code should look like at the end. That way they can compare against it if things are not working as expected.

**Comment by darwinzer0** [comment]
@zurgi, I have made the requested changes, and I've added a full version of the final working contract to my repo so people can refer to that if they get stuck at any time.

**Comment by zurgl** [comment]
@darwinzer0 I've reviewed your writing and everything look great for me. Thanks for your outstanding work, it was a pleasure to go through it. Do not hesitate to come back to us with new tutorial on secret.

@guillaumegaluz @yash-sharma1 @pyr0gan You can merge the branch.

**Comment by pyr0gan** [comment]
@darwinzer0 @zurgl  Just need to axe the .DS_Store files that are conflicting (add .DS_Store to .gitignore would be my suggestion 👍) 

Perhaps we should add this to the template @yash-sharma1 @zurgl ?

Screen Shot 2021-08-16 at 11 51 01 AM

**Comment by guillaumegaluz** [comment]
@zurgl you should have perms to merge now no?

**Pull request merged**
